language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux
dist: bionic

before_install:
  - sudo apt update
  - sudo apt -y install php-pcov

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit
