language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux
dist: bionic

before_script:
  - pecl install pcov
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php composer.phar require --dev pcov/clobber
  - ./vendor/bin/pcov clobber

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
