language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux
dist: bionic

before_script:
  - pecl install pcov
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require --dev pcov/clobber
  - php composer.phar install --dev

script: phpunit
